POST http://localhost:8080/user.php
Content-Type: application/json

{
    "name": "John Doe",
    "email": "8H4Zo@example.com",
    "password": "password123",
    "phone_number": 21412421,
    "role": "user"
}
